language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk6
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

branches:
  only:
  - master

notifications:
  email: false

script: ant build
