
language: java

matrix:
  include:
    ## https://docs.travis-ci.com/user/reference/trusty/
    ## has newer Maven
    - os: linux
      sudo: false
      dist: trusty
      jdk: oraclejdk8
      install: true
      env: FAILURES_ALLOWED=false

    ## OpenJDK should work too, but TravisCI has no up2date Ubuntu-Image, makes it impossible to install OpenJFX
    - os: linux
      sudo: false
      dist: trusty
      jdk: oraclejdk9
      install: true
      env: FAILURES_ALLOWED=false


    ## OS X 10.11
    - os: osx
      osx_image: xcode8
      env: FAILURES_ALLOWED=false
    ## OS X 10.12
    - os: osx
      osx_image: xcode8.3
      env: FAILURES_ALLOWED=false
    ## OS X 10.12
    - os: osx
      osx_image: xcode9.2
      env: FAILURES_ALLOWED=false

  allow_failures:
    - env: FAILURES_ALLOWED=true

branches:
  only:
  - master

notifications:
  email: false

script: ant build
